---
language: python
python: "2.7"

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en

install:
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt

before_script: "flake8 --ignore=E402 --max-line-length=100 --show-source --count ."

script: "python setup.py test"
